apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-gzjpocyf
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-gzjpocyf:967bca440865946533294a211953839bfbe158d3@sha256:d262361c614b5760312241182368ff2b7e3c235cd4f07a4642b0f3bc56e7638c
        name: container-image  
